### ISSUE TITLE
Is there any solution to build this on node 8+ ?

### ISSUE THREAD

**Issue by vkartaviy** [strongloop/strong-agent#13]
```
$ node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.9.2 | darwin | x64
gyp info spawn /usr/local/bin/python2
gyp info spawn args [ '/usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '~/development/agent/node_modules/strong-agent/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '~/.node-gyp/8.9.2/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=~/.node-gyp/8.9.2',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=~/.node-gyp/8.9.2/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=~/development/agent/node_modules/strong-agent',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/strong-agent/src/strong-agent.o
In file included from ../src/strong-agent.cc:6:
In file included from ../src/strong-agent.h:166:
../src/compat-inl.h:219:25: warning: 'GetDebugContext' is deprecated [-Wdeprecated-declarations]
      return v8::Debug::GetDebugContext(isolate);
                        ^
~/.node-gyp/8.9.2/include/node/v8-debug.h:208:3: note: 'GetDebugContext' has been explicitly marked
      deprecated here
  V8_DEPRECATED("Use v8-inspector",
  ^
~/.node-gyp/8.9.2/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
In file included from ../src/strong-agent.cc:6:
In file included from ../src/strong-agent.h:166:
../src/compat-inl.h:234:18: error: no member named 'GetMirror' in 'v8::Debug'
      v8::Debug::GetMirror(isolate->GetCurrentContext(),
      ~~~~~~~~~~~^
1 warning and 1 error generated.
make: *** [Release/obj.target/strong-agent/src/strong-agent.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 17.3.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/bin/node-gyp" "rebuild"
gyp ERR! cwd ~/development/agent/node_modules/strong-agent
gyp ERR! node -v v8.9.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
```

**Comment by bnoordhuis** [comment]
All functionality has been migrated to https://github.com/RuntimeTools/appmetrics after the acquisition.  It supports Node.js 8.

If you have a support contract and switching to appmetrics is not an option for you, I can look into updating strong-agent.

**Comment by vkartaviy** [comment]
Thanks. Appmetrics is ok for me. I am looking for monitoring solution and didn't know about migration, thought these are separate products.
