### ISSUE TITLE
CPU profiling hangs the process with node 0.12.3

### ISSUE THREAD

**Issue by tehsenaus** [strongloop/strong-agent#4]
I'm trying to invoke the cpu profiler, like so:
```
strongAgent.metrics.startCpuProfiling();
```

This causes the process to hang - it appears to be deadlocked. Here's the output from GDB:
```
(gdb) backtrace
#0  0x00007f6e95b98264 in __lll_lock_wait () from /lib64/libpthread.so.0
#1  0x00007f6e95b93508 in _L_lock_854 () from /lib64/libpthread.so.0
#2  0x00007f6e95b933d7 in pthread_mutex_lock () from /lib64/libpthread.so.0
#3  0x0000000000a8313f in v8::internal::Isolate::EnsureInitialized() ()
#4  0x0000000000a831fd in v8::internal::ThreadId::GetCurrentThreadId() ()
#5  0x0000000000ba13ac in v8::internal::SignalHandler::HandleProfilerSignal(int, siginfo*, void*) ()
#6  <signal handler called>
#7  0x00007f6e95b947b3 in pthread_mutex_unlock () from /lib64/libpthread.so.0
#8  0x0000000000a831fd in v8::internal::ThreadId::GetCurrentThreadId() ()
#9  0x0000000000812124 in v8::HandleScope::HandleScope(v8::Isolate*) ()
#10 0x0000000000cc8d23 in node::TimerWrap::OnTimeout(uv_timer_s*) ()
#11 0x0000000000e157ba in uv__run_timers (loop=0x15eb280) at ../deps/uv/src/unix/timer.c:165
#12 0x0000000000e0a510 in uv_run (loop=0x15eb280, mode=UV_RUN_ONCE) at ../deps/uv/src/unix/core.c:338
#13 0x0000000000c9cbe1 in node::Start(int, char**) ()
#14 0x00007f6e95814d5d in __libc_start_main () from /lib64/libc.so.6
#15 0x00000000006ac429 in _start ()
```

**Comment by bnoordhuis** [comment]
Hi @tehsenaus, thanks for the bug report.  Going by the stack trace, it's almost certainly a bug in V8, not strong-agent.

Is this blocking you?  We can look into it if you have a support contract with us.
